name: WHL Package

on:
  push:
    branches:
      - '*'

jobs:
  Test_python_38:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: docker build -f docker/run_tests_python_38.Dockerfile . -t mordineznlp:test-p38

      - name: Test code
        run: docker run mordineznlp:test-p38

  Test_python_37:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build image
        run: docker build -f docker/run_tests_python_37.Dockerfile . -t mordineznlp:test-p37

      - name: Test code
        run: docker run mordineznlp:test-p37

  Test_python_36:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build image
        run: docker build -f docker/run_tests_python_36.Dockerfile . -t mordineznlp:test-p36

      - name: Test code
        run: docker run mordineznlp:test-p36

  Build_WHL:
    needs: [Test_python_38, Test_python_37, Test_python_36]
    if: github.ref == 'refs/heads/test' || github.ref == 'refs/heads/devops'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: mkdir dist
        run: mkdir dist

      - name: Build Docker builder
        run: docker build -f docker/build_WHL.Dockerfile . -t mordineznlp:whl-builder

      - name: Build WHL
        run: docker run -v /home/runner/work/MordinezNLP/MordinezNLP/dist:/usr/src/app/dist mordineznlp:whl-builder

      - name: Archive WHL
        uses: actions/upload-artifact@v2
        with:
          name: MordinezNLP-WHL
          path: dist/

  Publish_WHL_test_pypi:
    needs: Build_WHL
    if: github.ref == 'refs/heads/test' || github.ref == 'refs/heads/devops'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: mkdir dist
        run: mkdir dist

      - name: Download WHL artifact
        uses: actions/download-artifact@v2
        with:
          name: MordinezNLP-WHL
          path: dist/

      - name: Build Docker builder
        run: docker build -f docker/publish_WHL.Dockerfile . -t mordineznlp:whl-publisher

      - name: Build WHL
        run: docker run  --env PYPIPASS=${PYPIPASS} --env PYPIREPO=testpypi mordineznlp:whl-publisher
        env:
          PYPIPASS: ${{ secrets.PYPIPASS_TEST }}
