name: Test and build WHL on push

on:
  pull_request:
    branches:
      - '**'

jobs:
  Test_python_38:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: docker build -f docker/run_tests_python_38.Dockerfile . -t mordineznlp:test-p38

      - name: Test code
        run: docker run mordineznlp:test-p38

  Test_python_37:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build image
        run: docker build -f docker/run_tests_python_37.Dockerfile . -t mordineznlp:test-p37

      - name: Test code
        run: docker run mordineznlp:test-p37

  Test_python_36:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build image
        run: docker build -f docker/run_tests_python_36.Dockerfile . -t mordineznlp:test-p36

      - name: Test code
        run: docker run mordineznlp:test-p36
